### ISSUE TITLE
Missing properties and classes related to location

### ISSUE THREAD

**Issue by SvenLieber** [belgif/fedvoc#23] opened 2022-08-29 15:29 UTC
I noticed that the URI of the class <http://vocab.belgif.be/ns/location#Municipality>, which is mentioned in the Excel sheet of this repository, does not resolve. Apparently there is no `location` model on the website vocab.belgif.be.

However, I do find some location-related skos concepts in the `authsrc-element` taxonomy: https://vocab.belgif.be/auth/authsrc-element/LOCN

What is the recommended way to use fedvoc for location information, e.g. to refer to a municipality?

Furthermore I found some available territory data using skos and terms of the geonames ontology (example [Belgium](https://github.com/belgif/vocab-belgif/blob/master/prod/data/codelist/territory.nt#L292-L312)), is this one way to model it? Yet the question remains with which property I should refer to a municipality modelled in such a way.

**Comment by barthanssens** [comment] 2022-09-08 09:37
In terms of classes and properties, they can/should certainly be published on vocab.belgif.be, but they should be published as part of https://vocab.belgif.be/ns?lang=en (as OWL/RDFS)

@MarcBruyland  can you provide an OWL / RDFS file in Turtle (similar to e.g. infosec https://vocab.belgif.be/ns/infosec.ttl)

**Comment by smals-vea** [comment] 2022-10-04 07:35
Request: make the URI’s dereferenceable on the site [vocab.belgif.be](http://vocab.belgif.be/)

Scope: location only or full scope (proposal: full scope)

Check: [Vocab Belgif](https://vocab.belgif.be/ns?lang=en) (GDPR - N-Triples) - need for a script to transform fedvoc to triples

**Decision: ok to publish the standard vocabulary terms on belgif.**

Note: the ICEG URI standard refers to using ‘http’ rather than ‘https’  in the URI.

**Comment by MarcBruyland** [comment] 2022-11-07 09:41
First draft publication: 
See https://vocab.belgif.be/ns/fedvoc?lang=en

**Comment by MarcBruyland** [comment] 2022-12-05 08:48
The issue is closed as agreed in the functional workgroup meeting of 2022-12-02.

**Closed by MarcBruyland** 2022-12-05 08:48 UTC
